server:
  port: 8081
spring:
  application:
    name: x-messenger
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/x_messenger
    username: otus_x
    password: otus_x
  liquibase:
    changeLog: "classpath:changelog/changelog.xml"
    default-schema: "public"
messenger:
  auth:
    basic-url: http://localhost:8080
    path: /user
management:
  endpoint:
    health:
      enabled: true