services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    command: --logging.level.zipkin2=TRACE
  postgresql-leader:
    image: docker.io/bitnami/postgresql:16
    container_name: leader
    volumes:
      - 'otus_x_user_db:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=otus_x
      - POSTGRESQL_PASSWORD=otus_x
      - POSTGRESQL_DATABASE=otus_x
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-follower:
    image: docker.io/bitnami/postgresql:16
    deploy:
      replicas: 2
    depends_on:
      - postgresql-leader
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-leader
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
  database:
    image: postgres:16.2
    container_name: messenger-db
    volumes:
      - 'postgresql_messenger:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=otus_x
      - POSTGRES_PASSWORD=otus_x
      - POSTGRES_DB=x_messenger
  user-service:
    image: kurov1993/otus-x:0.2
    container_name: user-service
    ports:
      - 8080:8080
    depends_on:
      - postgresql-follower
    environment:
      SPRING_DATASOURCE_WRITE_URL: jdbc:postgresql://leader:5432/otus_x
      SPRING_DATASOURCE_READ_URL: jdbc:postgresql://postgresql-follower:5432/otus_x
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  message-service:
    image: kurov1993/x-messenger:0.3
    container_name: x-messenger
    ports:
      - 8081:8081
    depends_on:
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://messenger-db:5432/x_messenger
      MESSENGER_AUTH_BASIC_URL: http://user-service:8080
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
volumes:
  postgresql_messenger:
    driver: local
  otus_x_user_db:
    driver: local