services:
  tarantool:
    build: ./schema
    container_name: in_memory
    ports:
      - "3301:3301"
    volumes:
      - 'tarantool_vol:/var/lib/tarantool'
  postgresql-leader:
    image: docker.io/bitnami/postgresql:16
    container_name: user_leader
    volumes:
      - 'otus_x_user_db:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=otus_x
      - POSTGRESQL_PASSWORD=otus_x
      - POSTGRESQL_DATABASE=otus_x
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-follower:
    image: docker.io/bitnami/postgresql:16
    depends_on:
      - postgresql-leader
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-leader
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
  user-service:
    image: kurov1993/otus-x:0.1
    container_name: user-service
    ports:
      - 8080:8080
    depends_on:
      - postgresql-follower
    environment:
      SPRING_DATASOURCE_WRITE_URL: jdbc:postgresql://user_leader:5432/otus_x
      SPRING_DATASOURCE_READ_URL: jdbc:postgresql://postgresql-follower:5432/otus_x
volumes:
  tarantool_vol:
    driver: local
  otus_x_user_db:
    driver: local